### ISSUE TITLE
How to delete old data

### ISSUE THREAD

**Issue by user646346** [spotify/XCMetrics#41]
Hello, Im trying to use docker-compose-local.yml and my postgres database is growing
Is there any build in solution to delete old data? Or I can just drop old partitions?

**Comment by BalestraPatrick** [comment]
You can just drop partitions if you don't need the data. Make sure to have backups otherwise somewhere else. We never delete our data so we haven't had the need to do this, but you keep in mind that you'll need to drop all partitions from all tables for the same days. You can likely do it with some magic queries to drop them all automatically.

**Comment by user646346** [comment]
Thanks

**Comment by 1ucas** [comment]
I'm in the same situation here.

To keep a weekly report, is it safe to just

DELETE FROM build_XYZ
WHERE day < (now() - '7'::interval)
on all tables starting with the "build" prefix?

I should keep "job_entries" and "migrations" untouched, right?
